# Cryptography and SSL/TLS Toolkit
brew "openssl@3"
# Play, record, convert, and stream select audio and video codecs
brew "ffmpeg"
# GitHub command-line tool
brew "gh"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# General-purpose data compression with high compression ratio
brew "xz"
# Development kit for the Java programming language
brew "openjdk"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Library for command-line editing
brew "readline"
# Interpreted, interactive, object-oriented programming language
brew "python@3.14"
# Mac App Store command-line interface
brew "mas"
# NCurses Disk Usage
brew "ncdu"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Safe, concurrent, practical language
brew "rust"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Agent orchestration platform
cask "antigravity"
# Bitcoin client and wallet
cask "bitcoin-core"
# Anthropic's official Claude AI desktop app
cask "claude"
# Universal database tool and SQL client
cask "dbeaver-community"
cask "font-jetbrains-mono"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "gcloud-cli"
# Web browser
cask "google-chrome"
# Client for the Google Drive storage service
cask "google-drive"
# Free and open-source RSS reader
cask "netnewswire"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Replacement for Docker Desktop
cask "orbstack"
# Multimedia player
cask "vlc"
# Multiplayer code editor
cask "zed"
# Video communication and virtual meeting platform
cask "zoom"
mas "Numbers", id: 361304891
mas "Xcode", id: 497799835
go "golang.org/x/tools/gopls"
cargo "atuin"
cargo "starship"
npm "esbuild"
npm "firebase-tools"
